create PROCEDURE spSplitFullname
@Fullname varchar(50),
@FIRSTNAME VARCHAR(40) OUTPUT,
@LASTNAME VARCHAR(40) OUTPUT

As
BEGIN
DECLARE @LEN INT

  SET @LEN = LEN(@FULLNAME)

  SET @FIRSTNAME =  SUBSTRING(@FULLNAME , 1, CHARINDEX(' ',@FULLNAME))
  SET @LASTNAME = SUBSTRING(@FULLNAME,CHARINDEX(' ',@Fullname)+1, LEN(@FULLNAME))
  
END


